version: 2
jobs:
  build:
    docker:
      - image: oraclelinux
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build -t base-docker-image:latest .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push aburan28/base-docker-image:latest
